# Generated by Django 4.1.5 on 2023-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0002_dentist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default=None, upload_to='dentalcareapp/files/images/patients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentist',
            name='image',
            field=models.ImageField(upload_to='dentalcareapp/files/images/dentists'),
        ),
    ]
