# Generated by Django 4.1.5 on 2023-01-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0003_patient_image_alter_dentist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
