# Generated by Django 4.1.5 on 2023-01-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0004_patient_address_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalcareapp.dentist'),
        ),
    ]
