# Generated by Django 4.1.5 on 2023-02-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0006_alter_dentist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dentalcareapp/files/images/dentists'),
        ),
    ]
