# Generated by Django 4.1.5 on 2023-02-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0007_alter_dentist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentalcareapp.dentist'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dentalcareapp/files/images/patients'),
        ),
    ]
