# Generated by Django 4.2.5 on 2023-09-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0008_alter_patient_dentist_alter_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='image',
        ),
    ]
