# Generated by Django 4.2.5 on 2023-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0010_dentist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dentist',
            name='repeat_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='repeat_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
