# Generated by Django 4.2.5 on 2023-10-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0011_dentist_password_dentist_repeat_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='repeat_password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='repeat_password',
        ),
    ]
