# Generated by Django 4.2.5 on 2023-10-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalcareapp', '0012_remove_dentist_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
